### ISSUE TITLE
Fast Role Swap?

### ISSUE THREAD

**Issue by topherbuckley** [arturo182/serpente_hw#2]
When you say:

>Powered either from USB or external source

Does this include the ability to hot swap between them as in meeting the Fast Role Swap USB standard? I'm hoping to design something that plugs into a smartphone and uses the smartphone as a power source until plugged into an external power source without shutting down the microcontroller.

**Comment by arturo182** [comment]
Hi,

As you can see in the schematic, the power selection uses diodes to protect from feeding back the voltage to the other source:
![image](https://user-images.githubusercontent.com/249082/97279276-18043c80-183b-11eb-92bc-1f964c514e34.png)

This means having two sources connected at the same time and then removing one of them should be safe and should not reset the microcontroller.

**Comment by topherbuckley** [comment]
Ah ok, so I guess this will not work because of this actually. I was hoping to charge the smartphone (sink) when connected to external power, but this diode configuration would not allow this it seems. 

Also it is my understanding that a simple switch will not swap the roles from source to sink, and a Power Delivery controller is necessary. 

Curious though, have you tried communicating with an Android phone with these? I may still have an alternate use for them if so.

**Comment by arturo182** [comment]
Yes, I used the Type-C Plug with my phone and the board shows up as a hardware keyboard so you can send keys to your phone and I believe there's more you can do with CircuitPython and Apple devices via USB but I haven't tried that, more details here: https://learn.adafruit.com/use-circuitpython-devices-with-iphone-ipad?view=all

**Comment by topherbuckley** [comment]
Cool! I see some use cases on android for CircuitPython as well. I'll likely pick up a few of these to fiddle with then. Who knows, maybe add a Power Delivery circuit at some point too!
